<?php
$_['d_translit'] = array(
	'translit_symbol_status' => 1,
	'translit_language_symbol_status' => 0,
	'transform_language_symbol_id' => 0,
	'trim_symbol_status' => 1,
	'translit_symbol' => array(),
	'translit_language_symbol' => array(),
	'trim_symbol' => array(),
	'transform_language_symbol' => array(
		'0' => array(
			'id'	=> '0',
			'name'	=> 'text_transform_none'
		),
		'1' => array(
			'id'	=> '1',
			'name'	=> 'text_transform_upper_to_lower'
		),
		'2' => array(
			'id'	=> '2',
			'name'	=> 'text_transform_lower_to_upper'
		),
	),
	'translit_symbol_default' => array(		
		'%' => '',
		'&amp;' => '',
		'\'' => '',
		'&quot;' => '',
		'(' => '',
		')' => '',
		',' => '',
		'.' => '',
		'/' => '-',
		'\\' => '-',		
		' ' => '-',
		'*' => '-',
		'+' => '-',
		'№' => '-',
		'=' => '-',	
		'\n' => '-',
		'\r' => '-',	
		'\t' => '-',			
	),
	'translit_language_symbol_default' => array(
		'а' => 'a',   
		'б' => 'b',   
		'в' => 'v',
		'г' => 'g',
		'д' => 'd',
		'е' => 'e',
		'є' => 'ye', 
		'ё' => 'yo',
		'ж' => 'zh',
		'з' => 'z',
		'і' => 'i', 
		'и' => 'i',
		'й' => 'j',
		'к' => 'k',
		'ї' => 'yi', 
		'л' => 'l',
		'м' => 'm',
		'н' => 'n',
		'о' => 'o',
		'п' => 'p',
		'р' => 'r',
		'с' => 's', 
		'т' => 't',
		'у' => 'u',
		'ф' => 'f',
		'х' => 'kh', 
		'ц' => 'ts',
		'ч' => 'ch',
		'ш' => 'sh',
		'щ' => 'shch',
		'ь' => '',
		'ы' => 'y',
		'ъ' => '',
		'э' => 'e',
		'ю' => 'yu', 
		'я' => 'ya',
		
		'А' => 'A', 
		'Б' => 'B', 
		'В' => 'V',
		'Г' => 'G', 
		'Д' => 'D', 
		'Е' => 'E', 
		'Є' => 'Ye',
		'Ё' => 'Yo', 
		'Ж' => 'Zh', 
		'З' => 'Z', 
		'І' => 'I',
		'И' => 'I', 
		'Й' => 'J',
		'К' => 'K', 
		'Ї' => 'Yi',
		'Л' => 'L',
		'М' => 'M', 
		'Н' => 'N',
		'О' => 'O',
		'П' => 'P',
		'Р' => 'R',
		'С' => 'S',
		'Т' => 'T', 
		'У' => 'U',
		'Ф' => 'F',
		'Х' => 'Kh', 
		'Ц' => 'Ts',
		'Ч' => 'Ch', 
		'Ш' => 'Sh',
		'Щ' => 'Shch',
		'Ь' => '',
		'Ы' => 'Y', 
		'Ъ' => '',
		'Э' => 'E', 
		'Ю' => 'Yu',
		'Я' => 'Ya',
	),
	'trim_symbol_default' => array(		
		'-'
	)
);

?>